# Generated by Django 5.2.1 on 2026-02-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_add_logo_to_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='google_verification_code',
            field=models.CharField(blank=True, help_text="google-site-verification=... ko'rinishidagi kod", max_length=255, null=True, verbose_name='Google Search Console tekshiruv kodi'),
        ),
    ]
